# Generated by Django 3.0.3 on 2022-02-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='organisation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
