# Generated by Django 3.0.3 on 2022-02-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0002_appuser_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='organisation',
        ),
        migrations.AddField(
            model_name='appuser',
            name='pfp',
            field=models.ImageField(default='default.png', upload_to='profile_pics/'),
        ),
    ]
