# Generated by Django 3.0.3 on 2022-02-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0004_auto_20220226_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='pfp',
            field=models.ImageField(default='default.png', upload_to='profile_pics/'),
        ),
    ]
