# Generated by Django 3.0.3 on 2022-02-27 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0009_auto_20220227_0955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
