# Generated by Django 3.0.3 on 2022-02-27 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0010_auto_20220227_0958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relationship',
            new_name='FriendRequest',
        ),
    ]
