# Generated by Django 3.0.3 on 2022-03-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0011_auto_20220227_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('accepted', 'accepted')], max_length=8),
        ),
    ]
