# Generated by Django 3.0.3 on 2022-03-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0012_auto_20220305_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
