# Generated by Django 3.0.3 on 2022-03-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0013_auto_20220305_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
